part of core_buckshotui_org;

// Copyright (c) 2012, John Evans
// https://github.com/prujohn/Buckshot
// See LICENSE file for Apache 2.0 licensing information.

class StringToColorStringConverter implements IValueConverter{

  const StringToColorStringConverter();

  dynamic convert(dynamic value, [dynamic parameter]){

    if (value.startsWith("#")){
      return value;
    }

    //reflection... please get here soon...
    switch(value){
      case "AliceBlue":
        return Colors.AliceBlue.toString();
      case "AntiqueWhite":
        return Colors.AntiqueWhite.toString();
      case "Aqua":
        return Colors.Aqua.toString();
      case "Aquamarine":
        return Colors.Aquamarine.toString();
      case "Azure":
        return Colors.Azure.toString();
      case "Beige":
        return Colors.Beige.toString();
      case "Bisque":
        return Colors.Bisque.toString();
      case "Black":
        return Colors.Black.toString();
      case "BlanchedAlmond":
        return Colors.BlanchedAlmond.toString();
      case "Blue":
        return Colors.Blue.toString();
      case "BlueViolet":
        return Colors.BlueViolet.toString();
      case "Brown":
        return Colors.Brown.toString();
      case "BurlyWood":
        return Colors.BurlyWood.toString();
      case "CadetBlue":
        return Colors.CadetBlue.toString();
      case "Chartreuse":
        return Colors.Chartreuse.toString();
      case "Chocolate":
        return Colors.Chocolate.toString();
      case "Coral":
        return Colors.Coral.toString();
      case "ConflowerBlue":
        return Colors.ConflowerBlue.toString();
      case "Cornsilk":
        return Colors.Cornsilk.toString();
      case "Crimson":
        return Colors.Crimson.toString();
      case "Cyan":
        return Colors.Cyan.toString();
      case "DarkBlue":
        return Colors.DarkBlue.toString();
      case "DarkCyan":
        return Colors.DarkCyan.toString();
      case "DarkGoldenrod":
        return Colors.DarkGoldenrod.toString();
      case "DarkGray":
        return Colors.DarkGray.toString();
      case "DarkGreen":
        return Colors.DarkGreen.toString();
      case "DarkKhaki":
        return Colors.DarkKhaki.toString();
      case "DarkMagenta":
        return Colors.DarkMagenta.toString();
      case "DarkOliveGreen":
        return Colors.DarkOliveGreen.toString();
      case "DarkOrange":
        return Colors.DarkOrange.toString();
      case "DarkOrchid":
        return Colors.DarkOrchid.toString();
      case "DarkRed":
        return Colors.DarkRed.toString();
      case "DarkSalmon":
        return Colors.DarkSalmon.toString();
      case "DarkSeaGreen":
        return Colors.DarkSeaGreen.toString();
      case "DarkSlateBlue":
        return Colors.DarkSlateBlue.toString();
      case "DarkSlateGray":
        return Colors.DarkSlateGray.toString();
      case "DarkTurquoise":
        return Colors.DarkTurquoise.toString();
      case "DarkViolet":
        return Colors.DarkViolet.toString();
      case "DeepPink":
        return Colors.DeepPink.toString();
      case "DeepSkyBlue":
        return Colors.DeepSkyBlue.toString();
      case "DimGray":
        return Colors.DimGray.toString();
      case "DodgerBlue":
        return Colors.DodgerBlue.toString();
      case "Firebrick":
        return Colors.Firebrick.toString();
      case "FloralWhite":
        return Colors.FloralWhite.toString();
      case "ForestGreen":
        return Colors.ForestGreen.toString();
      case "Fuchsia":
        return Colors.Fuchsia.toString();
      case "Gainsboro":
        return Colors.Gainsboro.toString();
      case "GhostWhite":
        return Colors.GhostWhite.toString();
      case "Gold":
        return Colors.Gold.toString();
      case "Goldenrod":
        return Colors.Goldenrod.toString();
      case "Gray":
        return Colors.Gray.toString();
      case "Green":
        return Colors.Green.toString();
      case "GreenYellow":
        return Colors.GreenYellow.toString();
      case "Honeydew":
        return Colors.Honeydew.toString();
      case "HotPink":
        return Colors.HotPink.toString();
      case "IndianRed":
        return Colors.IndianRed.toString();
      case "Indigo":
        return Colors.Indigo.toString();
      case "Ivory":
        return Colors.Ivory.toString();
      case "Khaki":
        return Colors.Khaki.toString();
      case "Lavender":
        return Colors.Lavender.toString();
      case "LavenderBlush":
        return Colors.LavenderBlush.toString();
      case "LawnGreen":
        return Colors.LawnGreen.toString();
      case "LemonChiffon":
        return Colors.LemonChiffon.toString();
      case "LightBlue":
        return Colors.LightBlue.toString();
      case "LightCoral":
        return Colors.LightCoral.toString();
      case "LightCyan":
        return Colors.LightCyan.toString();
      case "LightGoldenrod":
        return Colors.LightGoldenrod.toString();
      case "LightGray":
        return Colors.LightGray.toString();
      case "LightGreen":
        return Colors.LightGreen.toString();
      case "LightPink":
        return Colors.LightPink.toString();
      case "LightSalmon":
        return Colors.LightSalmon.toString();
      case "LightSeaGreen":
        return Colors.LightSeaGreen.toString();
      case "LightSkyBlue":
        return Colors.LightSkyBlue.toString();
      case "LightSlateGray":
        return Colors.LightSlateGray.toString();
      case "LightSteelBlue":
        return Colors.LightSteelBlue.toString();
      case "LightYellow":
        return Colors.LightYellow.toString();
      case "Lime":
        return Colors.Lime.toString();
      case "LimeGreen":
        return Colors.LimeGreen.toString();
      case "Linen":
        return Colors.Linen.toString();
      case "Magenta":
        return Colors.Magenta.toString();
      case "Maroon":
        return Colors.Maroon.toString();
      case "MediumAquamarine":
        return Colors.MediumAquamarine.toString();
      case "MediumBlue":
        return Colors.MediumBlue.toString();
      case "MediumOrchid":
        return Colors.MediumOrchid.toString();
      case "MediumPurple":
        return Colors.MediumPurple.toString();
      case "MediumSeaGreen":
        return Colors.MediumSeaGreen.toString();
      case "MediumSlateBlue":
        return Colors.MediumSlateBlue.toString();
      case "MediumSpringGreen":
        return Colors.MediumSpringGreen.toString();
      case "MediumTurquoise":
        return Colors.MediumTurquoise.toString();
      case "MediumVioletRed":
        return Colors.MediumVioletRed.toString();
      case "MidnightBlue":
        return Colors.MidnightBlue.toString();
      case "MintCream":
        return Colors.MintCream.toString();
      case "MistyRose":
        return Colors.MistyRose.toString();
      case "Moccasin":
        return Colors.Moccasin.toString();
      case "NavajoWhite":
        return Colors.NavajoWhite.toString();
      case "Navy":
        return Colors.Navy.toString();
      case "OldLace":
        return Colors.OldLace.toString();
      case "Olive":
        return Colors.Olive.toString();
      case "OliveDrab":
        return Colors.OliveDrab.toString();
      case "Orange":
        return Colors.Orange.toString();
      case "OrangeRed":
        return Colors.OrangeRed.toString();
      case "Orchid":
        return Colors.Orchid.toString();
      case "PaleGoldenrod":
        return Colors.PaleGoldenrod.toString();
      case "PaleGreen":
        return Colors.PaleGreen.toString();
      case "PaleTurquoise":
        return Colors.PaleTurquoise.toString();
      case "PaleVioletRed":
        return Colors.PaleVioletRed.toString();
      case "PapayaWhip":
        return Colors.PapayaWhip.toString();
      case "PeachPuff":
        return Colors.PeachPuff.toString();
      case "Peru":
        return Colors.Peru.toString();
      case "Pink":
        return Colors.Pink.toString();
      case "Plum":
        return Colors.Plum.toString();
      case "PowderBlue":
        return Colors.PowderBlue.toString();
      case "Purple":
        return Colors.Purple.toString();
      case "Red":
        return Colors.Red.toString();
      case "RosyBrown":
        return Colors.RosyBrown.toString();
      case "RoyalBlue":
        return Colors.RoyalBlue.toString();
      case "SaddleBrown":
        return Colors.SaddleBrown.toString();
      case "Salmon":
        return Colors.Salmon.toString();
      case "SandyBrown":
        return Colors.SandyBrown.toString();
      case "SeaGreen":
        return Colors.SeaGreen.toString();
      case "SeaShell":
        return Colors.SeaShell.toString();
      case "Sienna":
        return Colors.Sienna.toString();
      case "Silver":
        return Colors.Silver.toString();
      case "SkyBlue":
        return Colors.SkyBlue.toString();
      case "SlateBlue":
        return Colors.SlateBlue.toString();
      case "SlateGray":
        return Colors.SlateGray.toString();
      case "Snow":
        return Colors.Snow.toString();
      case "SpringGreen":
        return Colors.SpringGreen.toString();
      case "SteelBlue":
        return Colors.SteelBlue.toString();
      case "Tan":
        return Colors.Tan.toString();
      case "Teal":
        return Colors.Teal.toString();
      case "Thistle":
        return Colors.Thistle.toString();
      case "Tomato":
        return Colors.Tomato.toString();
      case "Turquoise":
        return Colors.Turquoise.toString();
      case "Violet":
        return Colors.Violet.toString();
      case "Wheat":
        return Colors.Wheat.toString();
      case "White":
        return Colors.White.toString();
      case "WhiteSmoke":
        return Colors.WhiteSmoke.toString();
      case "Yellow":
        return Colors.Yellow.toString();
      case "YellowGreen":
        return Colors.YellowGreen.toString();
      default:
        return Colors.White.toString();
    }
  }
}
